Change metadata map value type from String to Object
danieldai/android_metadata pull request #4
Opened 2021-01-28 02:34 UTC by SamuelHaws

A very simple change... addresses request for type generalization in https://github.com/danieldai/android_metadata/issues/2 and https://github.com/danieldai/android_metadata/issues/3. 

For the Flutter dev side: When you are pulling these values, you should cast them to whatever type you need, since they are coming in as Objects. For example, I'm trying to get some Strings from Android metadata where Integers present in the metadata were throwing the error mentioned in https://github.com/danieldai/android_metadata/issues/3. 
```dart
AndroidMetadata.metaDataAsMap.then((map) {
      String exampleString = map['com.centerstack.KEY_OF_VALUE_NEEDED'].toString();
    });
```

If other users want to make use of these changes while the PR is under review, please update your pubspec.yaml as such:
```yaml
android_metadata:
    git:
      url: https://github.com/SamuelHaws/android_metadata
```

Don't forget to run `flutter clean` and a fresh `flutter run` before using my fork. Cheers! 🥂

2021-01-28 07:33 UTC, danieldai commented
@SamuelHaws Thanks for your contribution. Since it looks like will not be compatible with the existing API, I will need some time to find a way that can take advantage of your good idea and keep compatibility at the same time. 

Thanks again！

2021-01-28 08:33 UTC, danieldai requested changes
The type of `String.valueOf(appInfo.metaData.get(key))` is still a `String`. so It seems it still can be put into a map of type `Map<String, String>`. so no need to change the type of map.

2021-01-29 08:45 UTC, danieldai commented
I will merge the commit and make a little change

2021-01-29 08:45 UTC, merged

2021-01-29 14:06 UTC, SamuelHaws commented
Hey, thanks @danieldai I apologize if it isn't entirely correct. I just needed to tweak it for my use cases and figured I'd pass it along. :) Thanks